version: "3.8"
services:
  postgres_admin:
    image: dpage/pgadmin4:5.1
    restart: always
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@dev.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    depends_on:
      - postgres
  
  postgres:
    image: postgres:13.2
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - '~/.services/postgres/data:/var/lib/postgresql/data'
      - './postgres.conf:/etc/postgresql/postgresql.conf'
      - './sql/init.sql:/docker-entrypoint-initdb.d/init.sql'

  redis:
    image: redis:6.2.1
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - '~/.services/redis/data:/data'
