# Every Vagrant development environment requires a box. You can search for
# boxes at https://vagrantcloud.com/search.
IMAGE_NAME = "hashicorp/bionic64"
COUNT = 2

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vbox|
    vbox.memory = 2048
    vbox.cpus = 2
  end

  config.vm.define "k8s-master" do |master|
    master.vm.box = IMAGE_NAME
    master.vm.network "private_network", ip: "192.168.50.10"
    master.vm.hostname = "k8s-master"
    master.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "ansible/master-playbook.yaml"
      ansible.extra_vars = {
        node_ip: "192.168.50.10",
      }
    end
  end

  (1..COUNT).each do |i|
    config.vm.define "k8s-worker-#{i}" do |worker|
      worker.vm.box = IMAGE_NAME
      worker.vm.network "private_network", ip: "192.168.50.#{i + 10}"
      worker.vm.hostname = "k8s-worker-#{i}"
      worker.vm.provision "ansible_local" do |ansible|
        ansible.playbook = "ansible/node-playbook.yaml"
        ansible.extra_vars = {
          node_ip: "192.168.50.#{i + 10}",
        }
      end
    end
  end

end
