CREATE DATABASE "Gitea";
CREATE ROLE svc_gitea WITH
	LOGIN
	NOSUPERUSER
	NOCREATEDB
	NOCREATEROLE
	INHERIT
	NOREPLICATION
	CONNECTION LIMIT -1
	PASSWORD 'gitea';
GRANT ALL ON DATABASE Gitea TO svc_gitea;